apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app
  namespace: k8s-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: k8s-app
        image: shaundevops/crowblock:latest  # Update with your Docker Hub username and image name
        ports:
        - containerPort: 80
  
